import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from Bio import Entrez
from datetime import datetime, timedelta
import os

# --- CONFIGURATION: Reading from Environment Variables for Security ---
# These are loaded from GitHub Secrets (or environment variables in PythonAnywhere)
EMAIL_SENDER = os.environ.get("EMAIL_SENDER")
EMAIL_PASSWORD = os.environ.get("EMAIL_PASSWORD") 
# EMAIL_RECEIVER_STR handles multiple recipients passed as a comma-separated string
EMAIL_RECEIVER_STR = os.environ.get("EMAIL_RECEIVER") 
ENTREZ_EMAIL = os.environ.get("ENTREZ_EMAIL") 

# Convert the receiver string to a list of emails for smtplib.sendmail()
if EMAIL_RECEIVER_STR:
    EMAIL_RECEIVER = [e.strip() for e in EMAIL_RECEIVER_STR.split(',')]
else:
    EMAIL_RECEIVER = []

# Search Keywords (can be updated here or made an environment variable)
KEYWORDS = ["mitochondrial disease", "mitochondrial DNA", "mtDNA", "mitochondrial DNA disease"]
# ---------------------

def fetch_articles():
    if not ENTREZ_EMAIL:
        print("Error: ENTREZ_EMAIL not set.")
        return []
        
    Entrez.email = ENTREZ_EMAIL
    
    # Calculate date range (Yesterday)
    yesterday = (datetime.now() - timedelta(days=1)).strftime("%Y/%m/%d")
    
    # Construct the PubMed query using OR operator for multiple terms
    search_terms = [f'"{term}"[Title/Abstract]' for term in KEYWORDS]
    pubmed_query_terms = " OR ".join(search_terms)
    search_query = f'({pubmed_query_terms}) AND {yesterday}[Date - Publication]'
    
    print(f"Searching for articles matching: ({pubmed_query_terms}) published on {yesterday}...")
    
    try:
        handle = Entrez.esearch(db="pubmed", term=search_query, retmax=20)
        record = Entrez.read(handle)
        handle.close()
        
        id_list = record["IdList"]
        if not id_list:
            print("No articles found in search results.")
            return []

        # Fetch details
        handle = Entrez.efetch(db="pubmed", id=id_list, rettype="medline", retmode="xml")
        articles = Entrez.read(handle)
        handle.close()
        
    except Exception as e:
        print(f"Error during PubMed API call: {e}")
        return []

    digest_data = []
    
    for article in articles.get('PubmedArticle', []):
        try:
            medline = article['MedlineCitation']['Article']
            title = medline.get('ArticleTitle', 'No Title')
            journal = medline.get('Journal', {}).get('Title', 'No Journal')
            
            # Get PMID and create Link
            pmid = article['MedlineCitation']['PMID']
            link = f"https://pubmed.ncbi.nlm.nih.gov/{pmid}/"

            # Author Logic
            author_list = medline.get('AuthorList', [])
            if not author_list:
                authors = "No Authors Listed"
            elif len(author_list) == 1:
                authors = f"{author_list[0].get('LastName', '')} {author_list[0].get('Initials', '')}"
            else:
                first = f"{author_list[0].get('LastName', '')} {author_list[0].get('Initials', '')}"
                last = f"{author_list[-1].get('LastName', '')} {author_list[-1].get('Initials', '')}"
                authors = f"{first} ... {last}"
            
            digest_data.append({
                'title': title,
                'authors': authors,
                'journal': journal,
                'url': link
            })
        except Exception as e:
            print(f"Skipping article due to parsing error: {e}")
            continue
            
    return digest_data

def format_html_email(data):
    html = """
    <html>
    <head>
    <style>
        table {width: 100%; border-collapse: collapse; font-family: Arial, sans-serif;}
        th {background-color: #003366; color: white; padding: 10px; text-align: left;}
        td {border-bottom: 1px solid #ddd; padding: 8px; text-align: left; vertical-align: top;}
        tr:nth-child(even) {background-color: #f2f2f2;}
        .title {font-weight: bold; color: #0056b3; text-decoration: none;}
        .title:hover {text-decoration: underline;}
        .journal {font-style: italic; color: #666;}
    </style>
    </head>
    <body>
    <h2>Daily Dai Lab Literature Digest</h2>
    <table>
        <tr>
            <th style="width: 50%;">Title (Click to Read)</th>
            <th style="width: 25%;">First & Last Author</th>
            <th style="width: 25%;">Journal</th>
        </tr>
    """
    
    for row in data:
        html += f"""
        <tr>
            <td><a href=\"{row['url']}\" class=\"title\">{row['title']}</a></td>
            <td>{row['authors']}</td>
            <td class=\"journal\">{row['journal']}</td>
        </tr>
        """
        
    html += """
    </table>
    <p><em>Generated by Dr. Zhiyu Dai using Google Gemini and Github</em></p>
    </body>
    </html>
    """
    return html

def send_email(html_content):
    if not EMAIL_SENDER or not EMAIL_PASSWORD or not EMAIL_RECEIVER:
        print("Error: Email credentials or receiver list not set.")
        return

    msg = MIMEMultipart()
    msg['From'] = EMAIL_SENDER
    # Use a comma-separated string for the 'To' header
    msg['To'] = ", ".join(EMAIL_RECEIVER)
    msg['Subject'] = f"Dai Lab Literature Digest: {KEYWORDS[0]} ({datetime.now().strftime('%Y-%m-%d')})"
    
    msg.attach(MIMEText(html_content, 'html'))
    
    try:
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(EMAIL_SENDER, EMAIL_PASSWORD)
        # Pass the list of recipients to sendmail()
        server.sendmail(EMAIL_SENDER, EMAIL_RECEIVER, msg.as_string())
        server.quit()
        print(f"Email successfully sent to {', '.join(EMAIL_RECEIVER)}")
    except Exception as e:
        print(f"Failed to send email: {e}")
        # Detailed error handling for authentication failure
        if 'authentication failed' in str(e).lower():
            print("Authentication failed. Ensure you are using a correct Google App Password, not your main account password.")

if __name__ == "__main__":
    if not EMAIL_PASSWORD or not ENTREZ_EMAIL:
        print("Agent could not run. Check that EMAIL_PASSWORD and ENTREZ_EMAIL environment variables are set.")
    else:
        data = fetch_articles()
        if data:
            html = format_html_email(data)
            send_email(html)
        else:
            print("No new articles found for yesterday. Email not sent.")
